Repository MACantara/CyberQuest, pull requests merged in 2025-07, with the labels that each got.

#92 Create the the misinformation maze cybersecurity scenario
  app/static/css/simulated-pc/windows.css
  app/static/images/level-one/senator-johnson.jpeg
  app/static/js/simulated-pc/base-dialogue.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/navigation.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/page-renderer.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/base-page.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/challenge1-page.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/components/article-content.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/components/sidebar.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/components/verification-tools.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/components/website-footer.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/components/website-header.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge2/challenge2-page.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge2/components/analysis-tools.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge2/components/investigation-form.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge2/components/source-comparison.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge2/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge3/challenge3-page.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge3/components/analysis-form.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge3/components/image-display.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge3/components/verification-tools.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge3/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge4/challenge4-page.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge4/components/assessment-form.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge4/components/investigation-tools.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge4/components/social-media-post.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge4/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/cross-reference-tool.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/location-verify.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/metadata-analyzer.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/reverse-image-search.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/tutorial.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/weather-verify.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/page-registry.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/file-manager-functions/window-tracker.js
  app/static/js/simulated-pc/desktop-components/shared-utils/navigation-util.js
  app/static/js/simulated-pc/desktop-components/window-base.js
  app/static/js/simulated-pc/desktop-components/window-manager.js
  app/static/js/simulated-pc/desktop-components/window-resize-manager.js
  app/static/js/simulated-pc/desktop-components/window-snap-manager.js
  app/static/js/simulated-pc/desktop.js
  app/static/js/simulated-pc/dialogue-manager.js
  app/static/js/simulated-pc/dialogues/levels/level-one/challenge1-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level-one/challenge2-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level-one/challenge3-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level-one/challenge4-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level-one/index.js
  app/static/js/simulated-pc/dialogues/levels/level-one/level-completion-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level1-misinformation-maze.js
Labels: new feature

#93 Create the shadow in the inbox cybersecurity scenario
  app/static/images/level-two/paypal.svg
  app/static/js/simulated-pc/base-tutorial.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/page-renderer.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge2/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge3/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge4/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-two/cyberquest-password-reset.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-two/microsoft-account-verify.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-two/paypal-account-confirm.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-two/secure-bank-verification.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-two/techcorp-document-portal.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/page-registry.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-action-handler.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-completion-tracker.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-read-tracker.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-security-manager.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-state.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/bank-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/base-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/company-update-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/cyberquest-welcome-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/email-registry.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/fake-microsoft-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/fake-paypal-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/legitimate-emails/cyberquest-welcome-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/newsletter-subscription.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/nigerian-prince-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/password-reset-legitimate.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/sophisticated-spear-phish.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/suspicious-emails/bank-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/suspicious-emails/nigerian-prince-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/file-manager-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/file-manager-functions/file-opener.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/file-viewer-apps/log-viewer-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/file-viewer-apps/text-viewer-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/network-monitor-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/system-logs-functions/log-filter.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/system-logs-functions/log-ui.js
  app/static/js/simulated-pc/desktop-components/window-snap-manager.js
  app/static/js/simulated-pc/dialogues/levels/level-two/email-security-completion-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level2-shadow-inbox.js
  app/static/js/simulated-pc/tutorials/browser-tutorial.js
Labels: new feature

#97 Merge latest changes from main
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/cyberquest-welcome-email.js
Labels: improvement

#100 Update the levels page to remove levels not to be implemented
  app/routes/levels.py
  app/static/js/simulated-pc/dialogues/dialogue-integration.js
  app/static/js/simulated-pc/dialogues/levels/level4-white-hat-test.js
  app/static/js/simulated-pc/dialogues/levels/level5-hunt-for-the-null.js
  app/static/js/simulated-pc/dialogues/levels/level5-social-web.js
  app/static/js/simulated-pc/dialogues/levels/level6-adaptive-adversary.js
  app/static/js/simulated-pc/dialogues/levels/level7-white-hat-test.js
  app/static/js/simulated-pc/dialogues/levels/level8-operation-blackout.js
Labels: improvement

#140 Convert the navigation control in level 1 into a progress bar only
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/challenge1-page.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/components/navigation-controls.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/components/progress-bar.js
Labels: improvement

#141 Remove the button for move to inbox for emails in the spam folder
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-action-handler.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-security-manager.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-state.js
Labels: remove feature

#145 Remove audio functionality from BootSequence class
  app/static/audio/Text_Sound_Effect.mp3
  app/static/js/simulated-pc/boot-sequence.js
Labels: remove feature

#147 Remove the rendering of suspicious website when loading another website in the browser
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/navigation.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/page-renderer.js
Labels: remove feature

#148 Refactor interactive labeljs into modular js files
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/interactive-labeling.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/interactive-labeling/analysis-calculator.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/interactive-labeling/interactive-ui.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/interactive-labeling/modal-manager.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/interactive-labeling/navigation-handler.js
Labels: refactor

#150 Update the tutorial for the level 1
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/challenge1-page.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/components/analysis-section.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/interactive-labeling/modal-manager.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/tutorial.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/page-registry.js
  app/static/js/simulated-pc/dialogues/levels/level-one/challenge1-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level-one/level-completion-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level1-misinformation-maze.js
Labels: improvement

#156 Refine the email security level summary to be similar to the misinformation level summary
  DIALOGUE_TRIGGERS.md
  app/routes/levels.py
  app/routes/profile.py
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/challenge1/utils/event-handlers.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/level-one/interactive-labeling/navigation-handler.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/news-site.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/browser-functions/pages/secure-bank.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-feedback.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/email-session-summary.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/email-functions/emails/nigerian-prince-email.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/malware-scanner-app.js
  app/static/js/simulated-pc/desktop-components/desktop-applications/ransomware-decryptor-app.js
  app/static/js/simulated-pc/dialogues/dialogue-integration.js
  app/static/js/simulated-pc/dialogues/dialogue-manager.js
  app/static/js/simulated-pc/dialogues/levels/level-one/level-completion-dialogue.js
  app/static/js/simulated-pc/dialogues/levels/level-three/index.js
  app/static/js/simulated-pc/dialogues/levels/level-three/level-three-completion.js
  app/static/js/simulated-pc/dialogues/levels/level-three/malware-scanning-intro.js
  app/static/js/simulated-pc/dialogues/levels/level-three/ransomware-decryption-intro.js
  app/static/js/simulated-pc/dialogues/levels/level3-malware-mayhem.js
  app/static/js/simulated-pc/dialogues/welcome-dialogue.js
  app/static/js/simulated-pc/shutdown-sequence.js
  app/templates/levels/levels.html
  app/templates/profile/dashboard.html
Labels: improvement
